### PR TITLE
fix(build): Add minified ESM builds

### PR DESCRIPTION
**Pull request by henrymyers**
## Description

It seemed a bit sad that we couldn't use the minified `uploadcare-widget` script through the react widget, so I decided to add support for it. You now output a minified ESM version of the all-locale build and the english-only build.

Both new builds do the same things:
* Replace the external `uploadcare-widget` import with the correct minified version  (`uploadcare.min` and `uploadcare.lang.en.min`)
* Use _rollup-plugin-terser_ to minify the react-widget output

Including the uploadcare-widget dependency,  the minified all-locale build saves around 240 KB and the minified english-only build saves around 327 KB.

## Checklist

- [ ] ~Tests (if applicable)~
- [x] Documentation (if applicable)
- [x] Changelog stub (or use [conventional commit messages](https://www.conventionalcommits.org/))

### CODE REVIEW

**Comment by nd0ut** [comment]
Hey @henrymyers 
Thanks for contribution. But what prevents you from doing minification on your side?

**Comment by henrymyers** [comment]
@nd0ut Mostly just a big codebase/build system spanning multiple teams, combined with a lack of time. This seemed like a quick win and made sense since your main uploadcare-widget package already offers minified and english-only bundles.

**Comment by henrymyers** [comment]
See the equivalent for uploadcare-widget-tab-effects [here](https://github.com/uploadcare/uploadcare-widget-tab-effects/pull/41)

**Comment by nd0ut** [comment]
Why did you put the folders `{en, en-min, min}` in the root instead of `dist/{en, en-min, min}`? Sure, the imports will be a bit weird with this `/dist/`, but I think it's better to keep consistency and not put the bundles at the root.

**Comment by henrymyers** [comment]
I actually started out by putting them in `dist`, then realized that you already had the `/en` directory at the root and changed my code to follow your existing pattern.

**Review by nd0ut — APPROVED** [review]

**Comment by nd0ut** [comment]
@shipjs prepare

**Pull request merged**
